# Generated by Django 2.2.6 on 2019-10-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.CharField(max_length=9999)),
                ('movie_name', models.CharField(max_length=100)),
                ('movie_desctiption', models.TextField()),
                ('movie_main_rating', models.FloatField()),
                ('movie_user_rating', models.FloatField()),
                ('movie_critics_raing', models.FloatField()),
                ('movie_url_image', models.CharField(max_length=1000)),
                ('movie_url_trailer', models.CharField(max_length=1000)),
                ('movie_country', models.CharField(choices=[('KZ', 'Kazakhstan'), ('RU', 'Russia'), ('USA', 'USA'), ('UK', 'Unighted Kingdom'), ('China', 'China')], max_length=100)),
                ('movie_budjet', models.FloatField()),
                ('movie_duration', models.TextField()),
                ('movie_date', models.DateField(verbose_name='Date of Premiere')),
                ('movie_findings', models.FloatField()),
            ],
        ),
    ]
