# Generated by Django 2.2.6 on 2019-10-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20191030_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_commented_users',
            field=models.ManyToManyField(related_name='Comments', through='mainapp.Comment', to='mainapp.User'),
        ),
    ]
