# Generated by Django 2.2.6 on 2019-10-30 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_movie_movie_commented_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_id',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='genre_id',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='movie_id',
        ),
        migrations.RemoveField(
            model_name='person',
            name='person_id',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='rating_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
    ]
