# Generated by Django 2.2.6 on 2019-11-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20191030_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
                ('country_name_russian', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='movie_country',
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_country',
            field=models.ManyToManyField(to='mainapp.Country'),
        ),
    ]
