# Generated by Django 2.2.6 on 2019-11-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20191103_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_password',
            field=models.CharField(default='qwe123ASD', max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='user_surname',
            field=models.CharField(default='UNKNOWN', max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_login',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=64),
        ),
    ]
