# Generated by Django 2.2.6 on 2019-11-12 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20191106_0156'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person_Movie',
            new_name='PersonMovie',
        ),
    ]
