# Generated by Django 2.2.6 on 2019-11-12 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20191113_0056'),
        ('mainapp', '0008_user_user_role'),
    ]

    operations = [
    ]
