# Generated by Django 2.2.7 on 2019-11-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_merge_20191113_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_status',
            field=models.CharField(default='not banned', max_length=16),
        ),
    ]
