# Generated by Django 2.2.7 on 2019-11-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_order_by_parameter',
            field=models.CharField(choices=[('movie_main_rating', 'movie_main_rating'), ('movie_critics_raing', 'movie_critics_raing'), ('movie_user_rating', 'movie_user_rating'), ('movie_date', 'movie_date')], default='movie_main_rating', max_length=32),
            preserve_default=False,
        ),
    ]
