# Generated by Django 2.2.7 on 2019-11-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20191113_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_movies',
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_categories',
            field=models.ManyToManyField(to='mainapp.Category'),
        ),
    ]
