# Generated by Django 2.2.6 on 2019-11-19 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20191113_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_liked_users',
            field=models.ManyToManyField(to='mainapp.User'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='mainapp.User'),
        ),
    ]
