# Generated by Django 2.2.6 on 2019-11-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_movie', models.ManyToManyField(to='mainapp.Movie')),
                ('favorite_user', models.ManyToManyField(to='mainapp.User')),
            ],
        ),
    ]
