# Generated by Django 2.2.6 on 2019-11-26 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='favorite_movie',
        ),
        migrations.AddField(
            model_name='favorite',
            name='favorite_movie',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Movie'),
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='favorite_user',
        ),
        migrations.AddField(
            model_name='favorite',
            name='favorite_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.User'),
        ),
    ]
