# Generated by Django 2.2.6 on 2019-12-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_user_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_critics_raing',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_desctiption',
            field=models.TextField(default=0.0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_main_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_url_image',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_user_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
