# Generated by Django 2.2.6 on 2019-12-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_auto_20191211_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/movies'),
        ),
    ]
