# Generated by Django 2.2.6 on 2019-12-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_movie_movie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
